### ISSUE TITLE
Reproducing bundles

### ISSUE THREAD

**Issue by milesfrain** [kl0tl/purescript-es-modules-benchmark#4]
I'm attempting to re-generate the bundles in this repo, but am encountering a few problems when running the Makefie:

1. `stack.yaml` points to an inaccessible purescript commit. Was history rewritten? I just updated it to point to your [latest commit](https://github.com/kl0tl/purescript/commit/e5b1798d3d3770bca57d79b0d78f1839332695bf).

2. That leads to issues with `purescript-ast` and `purescript-cst`. Looks like those live here now: https://github.com/purescript/purescript/tree/master/lib . Is this problem due to a mismatch between your fork PS fork and the zephyr PS dependency?

ast/cst errors for reference:
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for purescript-0.13.6:
    purescript-ast needed, but the stack configuration has no specified version (no package with that
                   name found, perhaps there is a typo in a package's build-depends or an omission from
                   the stack.yaml packages list?)
    purescript-cst needed, but the stack configuration has no specified version (no package with that
                   name found, perhaps there is a typo in a package's build-depends or an omission from
                   the stack.yaml packages list?)
needed due to purescript-es-modules-benchmark-1.0.0 -> purescript-0.13.6
```

I ended-up just punting on esm bundles. Interestingly, I am observing these differences in bundle sizes:
Original  | Mine | Bundle
 ---: | ---: | ---
 4511 | 4308 | webpack4-dce-bundle.js
 2638 | 1979 | webpack5-dce-bundle.js
 1115 | 1149 | webpack4-dce-bundle.min.js
  512 |  658 | parcel-dce-bundle.js
  413 |  338 | webpack5-dce-bundle.min.js
  276 |  297 | parcel-dce-bundle.min.js
  177 |  320 | rollup-dce-bundle.js
   82 |  150 | rollup-dce-bundle.min.js

**Edit:** The original post mentioned an issue with missing purs/terser bundle, but that's now resolved.

Now I'm wondering why the zephyr (dce) rollup bundles are twice as large.

Here's [my branch](https://github.com/milesfrain/purescript-es-modules-benchmark/tree/no-esm) which produced these results.

I also found that just using the binary from latest [zephyr release](https://github.com/coot/zephyr/releases) produces the same bundles as the latest zephyr-from-source, so I took out the stack dependency too.

**Comment by milesfrain** [comment]
>     * `purs-bundle` output is missing

Looks like that's an issue with `output/*/{foreign,index}.js` not expanding properly in the Makefile. ~What version of `make` are you using? I'm on 4.2.1, wondering if this works in 4.3.~

**Edit:** Found this was an issue with my makefile shell using the default `sh` rather than `bash`. Adding `SHELL=/bin/bash` fixed it. Works for both `make` 4.2.1 and 4.3. I'm curious why the original Makefile was working for you and how your shell was configured differently than the default.
* https://stackoverflow.com/questions/12838278/using-curly-brackets-for-variable-expansion-in-makefile-doesnt-work
* https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

~Also made some changes to how `webpack-cli` is installed so everything runs directly from a clean clone, rather than prompting and failing.~

**Edit:** Turns out these webpack-cli changes don't actually improve the situation. I don't know what's required to make this work smoothly from a clone.

**Comment by milesfrain** [comment]
Are these bundles supposed to work (log to dev console) if included in an `index.html`?:
```html
<!DOCTYPE html>    
<html>    
  <head>    
    <meta charset="UTF-8">    
    <title>Hi</title>    
  </head>    
  <body>    
    <script src="dist/purs-bundle.js"></script>    
  </body>    
</html>    
```

**Comment by kl0tl** [comment]
> 1. `stack.yaml` points to an inaccessible purescript commit. Was history rewritten?

Yeah sorry, I rebased this branch a few times already as other PR got merged.

> 2. That leads to issues with `purescript-ast` and `purescript-cst`.

Those packages were extracted in https://github.com/purescript/purescript/pull/3793. Here’s how to tell Stack about them:

```diff
 resolver: lts-13.26
 extra-deps:
   - git: git@github.com:coot/zephyr.git
     commit: 1f958fd512097038397eb99cef2c7705b6b5b2e4
   - git: git@github.com:kl0tl/purescript.git
-    commit: 5542a7db66b77111446201cbd3ae439512c3bb51
+    commit: e5b1798d3d3770bca57d79b0d78f1839332695bf
+    subdirs:
+      - '.'
+      - lib/purescript-ast
+      - lib/purescript-cst
   - happy-1.19.9
   - language-javascript-0.7.0.0
   - network-3.0.1.1
   - these-1.0.1
   - semialign-1
 flags:
   aeson-pretty:
     lib-only: true
   these:
     assoc: false
     quickcheck: false
```

> Adding `SHELL=/bin/bash` fixed it.

Is there a way to use `/usr/bin/env bash` instead?

> I don't know what's required to make this work smoothly from a clone.

What issues are you encountering with webpack?

> Are these bundles supposed to work (log to dev console) if included in an `index.html`?

No, you’ll need to add to the bundle some JavaScript file actually calling the main function.

Note that if you’re interested in comparing various bundlers results on a real app you may want to look at https://github.com/kl0tl/purescript-react-basic-todomvc instead.

**Comment by milesfrain** [comment]
> Note that if you’re interested in comparing various bundlers results on a real app you may want to look at https://github.com/kl0tl/purescript-react-basic-todomvc instead.

Thanks. Used that for inspiration to get the latest results [posted to discourse](https://discourse.purescript.org/t/what-is-the-state-of-the-art-minification-compression/1369/3).

> What issues are you encountering with webpack?

From a clean clone it would prompt me to install `webpack-cli` then fail, but get a little farther each time I'd rerun `make`. I believe 4 invocations were required to finally work. I think it's an issue with having a sub `package.json` in each of the webpack directories. I had better luck just removing webpack4 and adding the webpack5 dependency to the top level.

> Is there a way to use `/usr/bin/env bash` instead?

Not sure, although I'm pretty happy with the parcel2 + zephyr bundling strategy, so probably won't be digging much more into alternate bundling options.

Thanks for the help!
